name: cached_asset_image
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.2.1
  flutter_cache_manager: 3.4.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

dependency_overrides:
  vector_graphics: 1.1.19